
user defined: labelPlatform+labelHydr+601, spardyn,      
        labelPlatform+labelSNode+601, 
        orientation, reference, node, eye,
        length,     L_BP/20.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        surface,
            offset,     0.000, 
            cav,        CAV_BP,
            cdv,        CDV_BP,
            area,       A_BP,
            volume,     V_BP,
            norm,       1.0,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+602, spardyn,      
        labelPlatform+labelSNode+602, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+603, spardyn,      
        labelPlatform+labelSNode+603, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+604, spardyn,      
        labelPlatform+labelSNode+604, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+605, spardyn,      
        labelPlatform+labelSNode+605, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+606, spardyn,      
        labelPlatform+labelSNode+606, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+607, spardyn,      
        labelPlatform+labelSNode+607, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+608, spardyn,      
        labelPlatform+labelSNode+608, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+609, spardyn,      
        labelPlatform+labelSNode+609, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+610, spardyn,      
        labelPlatform+labelSNode+610, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+611, spardyn,      
        labelPlatform+labelSNode+611 , 
        orientation, reference, node, eye,
        length,     L_BP/20.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        surface,
            offset,     0.000, 
            cav,        CAV_BP,
            cdv,        CDV_BP,
            area,       A_BP,
            volume,     V_BP,
            norm,      -1.0,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";
