
user defined: labelPlatform+labelHydr+501, spardyn,      
        labelPlatform+labelSNode+501, 
        orientation, reference, node, eye,
        length,     L_BP/20.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        surface,
            offset,     0.000, 
            cav,        CAV_BP,
            cdv,        CDV_BP,
            area,       A_BP,
            volume,     V_BP,
            norm,       1.0,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+502, spardyn,      
        labelPlatform+labelSNode+502, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+503, spardyn,      
        labelPlatform+labelSNode+503, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+504, spardyn,      
        labelPlatform+labelSNode+504, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+505, spardyn,      
        labelPlatform+labelSNode+505, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+506, spardyn,      
        labelPlatform+labelSNode+506, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+507, spardyn,      
        labelPlatform+labelSNode+507, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+508, spardyn,      
        labelPlatform+labelSNode+508, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+509, spardyn,      
        labelPlatform+labelSNode+509, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+510, spardyn,      
        labelPlatform+labelSNode+510, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+511, spardyn,      
        labelPlatform+labelSNode+511 , 
        orientation, reference, node, eye,
        length,     L_BP/20.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        surface,
            offset,     0.000, 
            cav,        CAV_BP,
            cdv,        CDV_BP,
            area,       A_BP,
            volume,     V_BP,
            norm,      -1.0,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";
