joint : labelPlatform+labelJoint+1,
	total joint,
	labelPlatform+labelSNode+9,
		position            , reference, platformFrame, 0., 0., -16.5,
		position orientation, reference, platformFrame, eye ,
		rotation orientation, reference, platformFrame, eye ,
	labelPlatform+labelSNode+10,
		position            , reference, platformFrame, 0., 0., -16.5,
		position orientation, reference, platformFrame, eye ,
		rotation orientation, reference, platformFrame, eye ,
	position constraint,
		active, active, active, null,
	orientation constraint,
		active, active, active, null;