
user defined: labelPlatform+labelHydr+1, spardyn,      
        labelPlatform+labelSNode+1, 
        orientation, reference, node, eye,
        length,     L_CC/20.,
        diameter,   D_CC,
        ca,         CA_CC,
        cm,         CM_CC,
        cd,         CD_CC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+2, spardyn,      
        labelPlatform+labelSNode+2,  
        orientation, reference, node, eye,
        length,     L_CC/10.,
        diameter,   D_CC,
        ca,         CA_CC,
        cm,         CM_CC,
        cd,         CD_CC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+3, spardyn,      
        labelPlatform+labelSNode+3, 
        orientation, reference, node, eye,
        length,     L_CC/10.,
        diameter,   D_CC,
        ca,         CA_CC,
        cm,         CM_CC,
        cd,         CD_CC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+4, spardyn,      
        labelPlatform+labelSNode+4,  
        orientation, reference, node, eye,
        length,     L_CC/10.,
        diameter,   D_CC,
        ca,         CA_CC,
        cm,         CM_CC,
        cd,         CD_CC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+5, spardyn,      
        labelPlatform+labelSNode+5,   
        orientation, reference, node, eye,
        length,     L_CC/10.,
        diameter,   D_CC,
        ca,         CA_CC,
        cm,         CM_CC,
        cd,         CD_CC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+6, spardyn,      
        labelPlatform+labelSNode+6, 
        orientation, reference, node, eye,
        length,     L_CC/10.,
        diameter,   D_CC,
        ca,         CA_CC,
        cm,         CM_CC,
        cd,         CD_CC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+7, spardyn,      
        labelPlatform+labelSNode+7, 
        orientation, reference, node, eye,
        length,     L_CC/10.,
        diameter,   D_CC,
        ca,         CA_CC,
        cm,         CM_CC,
        cd,         CD_CC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+8, spardyn,      
        labelPlatform+labelSNode+8, 
        orientation, reference, node, eye,
        length,     L_CC/10.,
        diameter,   D_CC,
        ca,         CA_CC,
        cm,         CM_CC,
        cd,         CD_CC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+9, spardyn,      
        labelPlatform+labelSNode+9, 
        orientation, reference, node, eye,
        length,     L_CC/20.,
        diameter,   D_CC,
        ca,         CA_CC,
        cm,         CM_CC,
        cd,         CD_CC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+10, spardyn,      
        labelPlatform+labelSNode+10, 
        orientation, reference, node, eye,
        length,     L_CC/5.,
        diameter,   D_CC,
        ca,         CA_CC,
        cm,         CM_CC,
        cd,         CD_CC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        surface,
            offset,     -L_CC/10., 
            cav,        CAV_CC,
            cdv,        CDV_CC,
            area,       A_CC,
            volume,     V_CC,
            norm,      -1.0,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";
