
user defined: labelPlatform+labelHydr+201, spardyn,      
        labelPlatform+labelSNode+201, 
        orientation, reference, node, eye,
        length,     L_OC/20.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+202, spardyn,      
        labelPlatform+labelSNode+202, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+203, spardyn,      
        labelPlatform+labelSNode+203, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+204, spardyn,      
        labelPlatform+labelSNode+204, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+205, spardyn,      
        labelPlatform+labelSNode+205, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+206, spardyn,      
        labelPlatform+labelSNode+206, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+207, spardyn,      
        labelPlatform+labelSNode+207, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+208, spardyn,      
        labelPlatform+labelSNode+208, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+209, spardyn,      
        labelPlatform+labelSNode+209, 
        orientation, reference, node,  eye,
        length,     L_OC/20.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+210, spardyn,      
        labelPlatform+labelSNode+210, 
        orientation, reference, node, eye,
        length,     L_OC/5.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        surface,
            offset,     -L_OC/10., 
            cav,        CAV_OC,
            cdv,        CDV_OC,
            area,       A_OC,
            volume,     V_OC,
            norm,      -1.0,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";
