joint : labelPlatform+labelJoint+201,
	total joint,
	labelPlatform+labelSNode+209,
		position            , reference, outerColumn2Ref, 0., 0., -16.5,
		position orientation, reference, outerColumn2Ref, eye ,
		rotation orientation, reference, outerColumn2Ref, eye ,
	labelPlatform+labelSNode+210,
		position            , reference, outerColumn2Ref, 0., 0., -16.5,
		position orientation, reference, outerColumn2Ref, eye ,
		rotation orientation, reference, outerColumn2Ref, eye ,
	position constraint,
		active, active, active, null,
	orientation constraint,
		active, active, active, null;
