#number of joints: 80

#============================================================
# Joint: 41
#============================================================
joint: labelShell+labelJoint+41,
	total joint,
	labelShell+labelSNode+41,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,

	position constraint,
		active,
		active,
		active,
		null,
			#6.7588e#01, 0.0000e+00, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 42
#============================================================
joint: labelShell+labelJoint+42,
	total joint,
	labelShell+labelSNode+42,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#6.6756e#01, #1.0573e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 43
#============================================================
joint: labelShell+labelJoint+43,
	total joint,
	labelShell+labelSNode+43,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#6.4280e#01, #2.0886e#01, 7.3702e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 44
#============================================================
joint: labelShell+labelJoint+44,
	total joint,
	labelShell+labelSNode+44,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#6.0221e#01, #3.0684e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 45
#============================================================
joint: labelShell+labelJoint+45,
	total joint,
	labelShell+labelSNode+45,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#5.4680e#01, #3.9727e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 46
#============================================================
joint: labelShell+labelJoint+46,
	total joint,
	labelShell+labelSNode+46,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#4.7792e#01, #4.7792e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 47
#============================================================
joint: labelShell+labelJoint+47,
	total joint,
	labelShell+labelSNode+47,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#3.9727e#01, #5.4680e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 48
#============================================================
joint: labelShell+labelJoint+48,
	total joint,
	labelShell+labelSNode+48,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#3.0684e#01, #6.0221e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 49
#============================================================
joint: labelShell+labelJoint+49,
	total joint,
	labelShell+labelSNode+49,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#2.0886e#01, #6.4280e#01, 7.3702e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 50
#============================================================
joint: labelShell+labelJoint+50,
	total joint,
	labelShell+labelSNode+50,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#1.0573e#01, #6.6756e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 51
#============================================================
joint: labelShell+labelJoint+51,
	total joint,
	labelShell+labelSNode+51,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#1.3247e#15, #6.7588e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 52
#============================================================
joint: labelShell+labelJoint+52,
	total joint,
	labelShell+labelSNode+52,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#1.0573e#01, #6.6756e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 53
#============================================================
joint: labelShell+labelJoint+53,
	total joint,
	labelShell+labelSNode+53,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#2.0886e#01, #6.4280e#01, 7.3702e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 54
#============================================================
joint: labelShell+labelJoint+54,
	total joint,
	labelShell+labelSNode+54,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#3.0684e#01, #6.0221e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 55
#============================================================
joint: labelShell+labelJoint+55,
	total joint,
	labelShell+labelSNode+55,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#3.9727e#01, #5.4680e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 56
#============================================================
joint: labelShell+labelJoint+56,
	total joint,
	labelShell+labelSNode+56,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#4.7792e#01, #4.7792e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 57
#============================================================
joint: labelShell+labelJoint+57,
	total joint,
	labelShell+labelSNode+57,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#5.4680e#01, #3.9727e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 58
#============================================================
joint: labelShell+labelJoint+58,
	total joint,
	labelShell+labelSNode+58,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#6.0221e#01, #3.0684e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 59
#============================================================
joint: labelShell+labelJoint+59,
	total joint,
	labelShell+labelSNode+59,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#6.4280e#01, #2.0886e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 60
#============================================================
joint: labelShell+labelJoint+60,
	total joint,
	labelShell+labelSNode+60,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#6.6756e#01, #1.0573e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 61
#============================================================
joint: labelShell+labelJoint+61,
	total joint,
	labelShell+labelSNode+61,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#6.7588e#01, 6.8307e#16, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 62
#============================================================
joint: labelShell+labelJoint+62,
	total joint,
	labelShell+labelSNode+62,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#6.6756e#01, 1.0573e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 63
#============================================================
joint: labelShell+labelJoint+63,
	total joint,
	labelShell+labelSNode+63,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#6.4280e#01, 2.0886e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 64
#============================================================
joint: labelShell+labelJoint+64,
	total joint,
	labelShell+labelSNode+64,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#6.0221e#01, 3.0684e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 65
#============================================================
joint: labelShell+labelJoint+65,
	total joint,
	labelShell+labelSNode+65,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#5.4680e#01, 3.9727e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 66
#============================================================
joint: labelShell+labelJoint+66,
	total joint,
	labelShell+labelSNode+66,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#4.7792e#01, 4.7792e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 67
#============================================================
joint: labelShell+labelJoint+67,
	total joint,
	labelShell+labelSNode+67,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#3.9727e#01, 5.4680e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 68
#============================================================
joint: labelShell+labelJoint+68,
	total joint,
	labelShell+labelSNode+68,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#3.0684e#01, 6.0221e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 69
#============================================================
joint: labelShell+labelJoint+69,
	total joint,
	labelShell+labelSNode+69,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#2.0886e#01, 6.4280e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 70
#============================================================
joint: labelShell+labelJoint+70,
	total joint,
	labelShell+labelSNode+70,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#1.0573e#01, 6.6756e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 71
#============================================================
joint: labelShell+labelJoint+71,
	total joint,
	labelShell+labelSNode+71,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#4.9233e#16, 6.7588e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 72
#============================================================
joint: labelShell+labelJoint+72,
	total joint,
	labelShell+labelSNode+72,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#1.0573e#01, 6.6756e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 73
#============================================================
joint: labelShell+labelJoint+73,
	total joint,
	labelShell+labelSNode+73,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#2.0886e#01, 6.4280e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 74
#============================================================
joint: labelShell+labelJoint+74,
	total joint,
	labelShell+labelSNode+74,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#3.0684e#01, 6.0221e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 75
#============================================================
joint: labelShell+labelJoint+75,
	total joint,
	labelShell+labelSNode+75,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#3.9727e#01, 5.4680e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 76
#============================================================
joint: labelShell+labelJoint+76,
	total joint,
	labelShell+labelSNode+76,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#4.7792e#01, 4.7792e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 77
#============================================================
joint: labelShell+labelJoint+77,
	total joint,
	labelShell+labelSNode+77,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#5.4680e#01, 3.9727e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 78
#============================================================
joint: labelShell+labelJoint+78,
	total joint,
	labelShell+labelSNode+78,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#6.0221e#01, 3.0684e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 79
#============================================================
joint: labelShell+labelJoint+79,
	total joint,
	labelShell+labelSNode+79,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#6.4280e#01, 2.0886e#01, 7.3702e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 80
#============================================================
joint: labelShell+labelJoint+80,
	total joint,
	labelShell+labelSNode+80,
	position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	towerBeamBottom,
	   position, reference, towerSBInterface, null,
	   position orientation, reference, towerSBInterface, eye,
	   rotation orientation, reference, towerSBInterface, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#6.6756e#01, 1.0573e#01, 7.3701e#01,
			#const 6.7841e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 1
#============================================================
joint: labelShell+labelJoint+1,
	total joint,
	labelShell+labelSNode+1,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#1.0000e+00, 0.0000e+00, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 2
#============================================================
joint: labelShell+labelJoint+2,
	total joint,
	labelShell+labelSNode+2,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#9.8769e#01, #1.5643e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 3
#============================================================
joint: labelShell+labelJoint+3,
	total joint,
	labelShell+labelSNode+3,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#9.5106e#01, #3.0902e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 4
#============================================================
joint: labelShell+labelJoint+4,
	total joint,
	labelShell+labelSNode+4,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#8.9101e#01, #4.5399e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 5
#============================================================
joint: labelShell+labelJoint+5,
	total joint,
	labelShell+labelSNode+5,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#8.0902e#01, #5.8779e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 6
#============================================================
joint: labelShell+labelJoint+6,
	total joint,
	labelShell+labelSNode+6,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#7.0711e#01, #7.0711e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 7
#============================================================
joint: labelShell+labelJoint+7,
	total joint,
	labelShell+labelSNode+7,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#5.8779e#01, #8.0902e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 8
#============================================================
joint: labelShell+labelJoint+8,
	total joint,
	labelShell+labelSNode+8,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#4.5399e#01, #8.9101e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 9
#============================================================
joint: labelShell+labelJoint+9,
	total joint,
	labelShell+labelSNode+9,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#3.0902e#01, #9.5106e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 10
#============================================================
joint: labelShell+labelJoint+10,
	total joint,
	labelShell+labelSNode+10,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#1.5643e#01, #9.8769e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 11
#============================================================
joint: labelShell+labelJoint+11,
	total joint,
	labelShell+labelSNode+11,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#1.9600e#15, #1.0000e+00, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 12
#============================================================
joint: labelShell+labelJoint+12,
	total joint,
	labelShell+labelSNode+12,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#1.5643e#01, #9.8769e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 13
#============================================================
joint: labelShell+labelJoint+13,
	total joint,
	labelShell+labelSNode+13,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#3.0902e#01, #9.5106e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 14
#============================================================
joint: labelShell+labelJoint+14,
	total joint,
	labelShell+labelSNode+14,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#4.5399e#01, #8.9101e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 15
#============================================================
joint: labelShell+labelJoint+15,
	total joint,
	labelShell+labelSNode+15,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#5.8779e#01, #8.0902e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 16
#============================================================
joint: labelShell+labelJoint+16,
	total joint,
	labelShell+labelSNode+16,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#7.0711e#01, #7.0711e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 17
#============================================================
joint: labelShell+labelJoint+17,
	total joint,
	labelShell+labelSNode+17,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#8.0902e#01, #5.8779e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 18
#============================================================
joint: labelShell+labelJoint+18,
	total joint,
	labelShell+labelSNode+18,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#8.9101e#01, #4.5399e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 19
#============================================================
joint: labelShell+labelJoint+19,
	total joint,
	labelShell+labelSNode+19,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#9.5106e#01, #3.0902e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 20
#============================================================
joint: labelShell+labelJoint+20,
	total joint,
	labelShell+labelSNode+20,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#9.8769e#01, #1.5643e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 21
#============================================================
joint: labelShell+labelJoint+21,
	total joint,
	labelShell+labelSNode+21,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#1.0000e+00, 1.0106e#15, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 22
#============================================================
joint: labelShell+labelJoint+22,
	total joint,
	labelShell+labelSNode+22,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#9.8769e#01, 1.5643e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 23
#============================================================
joint: labelShell+labelJoint+23,
	total joint,
	labelShell+labelSNode+23,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#9.5106e#01, 3.0902e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 24
#============================================================
joint: labelShell+labelJoint+24,
	total joint,
	labelShell+labelSNode+24,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#8.9101e#01, 4.5399e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 25
#============================================================
joint: labelShell+labelJoint+25,
	total joint,
	labelShell+labelSNode+25,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#8.0902e#01, 5.8779e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 26
#============================================================
joint: labelShell+labelJoint+26,
	total joint,
	labelShell+labelSNode+26,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#7.0711e#01, 7.0711e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 27
#============================================================
joint: labelShell+labelJoint+27,
	total joint,
	labelShell+labelSNode+27,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#5.8779e#01, 8.0902e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 28
#============================================================
joint: labelShell+labelJoint+28,
	total joint,
	labelShell+labelSNode+28,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#4.5399e#01, 8.9101e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 29
#============================================================
joint: labelShell+labelJoint+29,
	total joint,
	labelShell+labelSNode+29,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#3.0902e#01, 9.5106e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 30
#============================================================
joint: labelShell+labelJoint+30,
	total joint,
	labelShell+labelSNode+30,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#1.5643e#01, 9.8769e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 31
#============================================================
joint: labelShell+labelJoint+31,
	total joint,
	labelShell+labelSNode+31,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#7.2843e#16, 1.0000e+00, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 32
#============================================================
joint: labelShell+labelJoint+32,
	total joint,
	labelShell+labelSNode+32,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#1.5643e#01, 9.8769e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 33
#============================================================
joint: labelShell+labelJoint+33,
	total joint,
	labelShell+labelSNode+33,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#3.0902e#01, 9.5106e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 34
#============================================================
joint: labelShell+labelJoint+34,
	total joint,
	labelShell+labelSNode+34,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#4.5399e#01, 8.9101e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 35
#============================================================
joint: labelShell+labelJoint+35,
	total joint,
	labelShell+labelSNode+35,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#5.8779e#01, 8.0902e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 36
#============================================================
joint: labelShell+labelJoint+36,
	total joint,
	labelShell+labelSNode+36,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#7.0711e#01, 7.0711e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 37
#============================================================
joint: labelShell+labelJoint+37,
	total joint,
	labelShell+labelSNode+37,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#8.0902e#01, 5.8779e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 38
#============================================================
joint: labelShell+labelJoint+38,
	total joint,
	labelShell+labelSNode+38,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#8.9101e#01, 4.5399e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 39
#============================================================
joint: labelShell+labelJoint+39,
	total joint,
	labelShell+labelSNode+39,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#9.5106e#01, 3.0902e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;

#============================================================
# Joint: 40
#============================================================
joint: labelShell+labelJoint+40,
	total joint,
	labelShell+labelSNode+40,
	position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	towerBaseFlange,
	   position, reference, towerBaseFrame, null,
	   position orientation, reference, towerBaseFrame, eye,
	   rotation orientation, reference, towerBaseFrame, eye,
	position constraint,
		active,
		active,
		active,
		null,
			#9.8769e#01, 1.5643e#01, 0.0000e+00,
			#const 4.5852e+00,
	orientation constraint,
		active,
		active,
		active,
		null;
