joint : labelPlatform+labelJoint+101,
	total joint,
	labelPlatform+labelSNode+109,
		position            , reference, outerColumn1Ref, 0., 0., -16.5,
		position orientation, reference, outerColumn1Ref, eye ,
		rotation orientation, reference, outerColumn1Ref, eye ,
	labelPlatform+labelSNode+110,
		position            , reference, outerColumn1Ref, 0., 0., -16.5,
		position orientation, reference, outerColumn1Ref, eye ,
		rotation orientation, reference, outerColumn1Ref, eye ,
	position constraint,
		active, active, active, null,
	orientation constraint,
		active, active, active, null;
