
user defined: labelPlatform+labelHydr+101, spardyn,      
        labelPlatform+labelSNode+101, 
        orientation, reference, node, eye,
        length,     L_OC/20.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+102, spardyn,      
        labelPlatform+labelSNode+102, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+103, spardyn,      
        labelPlatform+labelSNode+103, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+104, spardyn,      
        labelPlatform+labelSNode+104, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+105, spardyn,      
        labelPlatform+labelSNode+105, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+106, spardyn,      
        labelPlatform+labelSNode+106, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+107, spardyn,      
        labelPlatform+labelSNode+107, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+108, spardyn,      
        labelPlatform+labelSNode+108, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+109, spardyn,      
        labelPlatform+labelSNode+109, 
        orientation, reference, node,  eye,
        length,     L_OC/20.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+110, spardyn,      
        labelPlatform+labelSNode+110, 
        orientation, reference, node, eye,
        length,     L_OC/5.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        surface,
            offset,     -L_OC/10., 
            cav,        CAV_OC,
            cdv,        CDV_OC,
            area,       A_OC,
            volume,     V_OC,
            norm,      -1.0,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";
