
user defined: labelPlatform+labelHydr+401, spardyn,      
        labelPlatform+labelSNode+401, 
        orientation, reference, node, eye,
        length,     L_BP/20.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        surface,
            offset,     0.000, 
            cav,        CAV_BP,
            cdv,        CDV_BP,
            area,       A_BP,
            volume,     V_BP,
            norm,       1.0,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+402, spardyn,      
        labelPlatform+labelSNode+402, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+403, spardyn,      
        labelPlatform+labelSNode+403, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+404, spardyn,      
        labelPlatform+labelSNode+404, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+405, spardyn,      
        labelPlatform+labelSNode+405, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+406, spardyn,      
        labelPlatform+labelSNode+406, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+407, spardyn,      
        labelPlatform+labelSNode+407, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+408, spardyn,      
        labelPlatform+labelSNode+408, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+409, spardyn,      
        labelPlatform+labelSNode+409, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+410, spardyn,      
        labelPlatform+labelSNode+410, 
        orientation, reference, node, eye,
        length,     L_BP/10.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+411, spardyn,      
        labelPlatform+labelSNode+411 , 
        orientation, reference, node, eye,
        length,     L_BP/20.,
        diameter,   D_BP,
        ca,         CA_BP,
        cm,         CM_BP,
        cd,         CD_BP,
        rho,        waterDensity,
        gravity,    gravityAccel,
        surface,
            offset,     0.000, 
            cav,        CAV_BP,
            cdv,        CDV_BP,
            area,       A_BP,
            volume,     V_BP,
            norm,      -1.0,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";
