joint : labelPlatform+labelJoint+301,
	total joint,
	labelPlatform+labelSNode+309,
		position            , reference, outerColumn3Ref, 0., 0., -16.5,
		position orientation, reference, outerColumn3Ref, eye ,
		rotation orientation, reference, outerColumn3Ref, eye ,
	labelPlatform+labelSNode+310,
		position            , reference, outerColumn3Ref, 0., 0., -16.5,
		position orientation, reference, outerColumn3Ref, eye ,
		rotation orientation, reference, outerColumn3Ref, eye ,
	position constraint,
		active, active, active, null,
	orientation constraint,
		active, active, active, null;
