
user defined: labelPlatform+labelHydr+301, spardyn,      
        labelPlatform+labelSNode+301, 
        orientation, reference, node, eye,
        length,     L_OC/20.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+302, spardyn,      
        labelPlatform+labelSNode+302, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+303, spardyn,      
        labelPlatform+labelSNode+303, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+304, spardyn,      
        labelPlatform+labelSNode+304, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+305, spardyn,      
        labelPlatform+labelSNode+305, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+306, spardyn,      
        labelPlatform+labelSNode+306, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+307, spardyn,      
        labelPlatform+labelSNode+307, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+308, spardyn,      
        labelPlatform+labelSNode+308, 
        orientation, reference, node, eye,
        length,     L_OC/10.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+309, spardyn,      
        labelPlatform+labelSNode+309, 
        orientation, reference, node,  eye,
        length,     L_OC/20.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";

user defined: labelPlatform+labelHydr+310, spardyn,      
        labelPlatform+labelSNode+310, 
        orientation, reference, node, eye,
        length,     L_OC/5.,
        diameter,   D_OC,
        ca,         CA_OC,
        cm,         CM_OC,
        cd,         CD_OC,
        rho,        waterDensity,
        gravity,    gravityAccel,
        surface,
            offset,     -L_OC/10., 
            cav,        CAV_OC,
            cdv,        CDV_OC,
            area,       A_OC,
            volume,     V_OC,
            norm,      -1.0,
        force scale factor, reference, startUp,
        wave input file, "../../wave.ipt";
